name: TSun RDP Access

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Ngrok ğŸ“…
      run: Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip

    - name: Extract Ngrok ğŸ“¦
      run: Expand-Archive ngrok.zip

    - name: Authenticate Ngrok ğŸ”
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Enable Terminal Services (RDP) ğŸš€
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0

    - name: Enable Remote Desktop Firewall Rule ğŸ”¥
      run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"

    - name: Set RDP User Authentication ğŸ›¡ï¸
      run: Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1

    - name: Create RDP User Account ğŸ§‘â€ğŸ’»
      run: Set-LocalUser -Name "saeedxdie" -Password (ConvertTo-SecureString -AsPlainText "S@eedxdie1" -Force)

    - name: Create Ngrok TCP Tunnel for RDP ğŸ”—
      run: .\ngrok\ngrok.exe tcp 3389
